<?php

// Link to SuiteCRM documentation
// https://docs.suitecrm.com/developer/api/api-v4.1-methods/#_get_module_fields


// LIST OF EXAMPLES
// It is recommended to run the examples one at a time. To do this we can comment on the active example and uncomment another one.

// EXAMPLE 1
// Get information about the fields name, last name, email, age, document type and document identifier of the Contacts module

    // $params = array(
    //     'module_name' => 'Contacts',
    //     'fields' => array(
    //         'name',
    //         'last_name',
    //         'email1', 
    //         'stic_age_c', 
    //         'stic_identification_type_c', 
    //         'stic_identification_number_c'
    //     ),
    // );


// EXAMPLE 2
// Get information about all fields in the Registrations module, including fields generated by relationships.

    // $params = array(
    //     'module_name' => 'stic_Registrations',
    //     'fields' => array(),
    // );

    
// Execute the call to the corresponding API client function
$apiClient->getModuleFields($params);